version: "3"
services:
  1rabbitmqbeat:
    image: geocode.igd.fraunhofer.de:4567/bfranke/rabbitmq-beat:latest
    environment:
      - RABBITMQ_HOSTNAME=vm1
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWD=admin
      - RABBITMQ_EXCHANGE=logs
      - RABBITMQ_ROUTING_KEYS=["error.*","logs.*","warning.*"]
      - RABBITMQ_LOG_CONFIG=true
    network_mode: "host"