version: "3"
services:
  1rabbitmqbeat:
    image: rabbitmqbeat
    environment:
      - RABBITMQ_HOSTNAME=vm1
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWD=admin
      - RABBITMQ_EXCHANGE=logs
      - RABBITMQ_ROUTING_KEYS=["ellor.*","lbgs.*","warning.*"]
    network_mode: "host"